# Generated by Django 5.1.5 on 2025-02-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moffet_bay', '0002_contactmessage_delete_documentation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_id',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
    ]
