# Generated by Django 5.1.5 on 2025-02-23 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Moffet_bay', '0004_attraction'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attraction',
            new_name='Attractions',
        ),
    ]
